version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'Borges'
      POSTGRES_USER: 'ADMIN'
      POSTGRES_PASSWORD: 'PASS'
    ports:
      - "5432:5432"
  redis:
    image: redis
  application:
    build: .
    command: python InternetLibrary/run.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - redis
