version: '3'

services:
  redis:
    image: redis
  application:
    build: .
    command: python InternetLibrary/app.py &&
      export FLASK_ENV=development &&
      export DATABASE_URL= postgres://0.0.0.0:5432/Borges
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - redis
